export enum CommandStatus {
    REQUESTED = "REQUESTED",
    NOT_SUPPORTED = "NOT_SUPPORTED",
    REJECTED = "REJECTED",
    ACCEPTED = "ACCEPTED",
    TIMEOUT = "TIMEOUT",
    UNKNOWN_SESSION = "UNKNOWN_SESSION"
}
