require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'SwiftProtobuf', '~> 1.0'

platform :ios, '11.0'

project 'Satimoto',
        'DebugTestnet' => :debug,
        'ReleaseTestnet' => :release,
        'DebugRegtest' => :debug,
        'ReleaseRegtest' => :release,
        'Debug' => :debug,
        'Release' => :release

target 'Satimoto' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'SatimotoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
      installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
      end
  end
end